name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/dotnet-ci.yml
    with:
      project: portal-auth/PortalAuth.csproj
      tests: PortalAuth.Tests/PortalAuth.Tests.csproj
      image: portal-auth
      context: portal-auth
      dockerfile: portal-auth/Dockerfile
